baseurl: ""
lang: en
timezone: Africa/Nairobi
permalink: /404.html
title: "Alvin Dereba"
tagline: "System Administrator"
description: "Linux system Administrator"
x_username: Kunnoh3
github_username: Kunnoh
url: "https://kunnoh.github.io/"
keywords: "Learn, Listen, Share, Write, Read"
pwa:
  enabled: true
github:
  username: kunnoh
twitter:
  username: Kunnoh3    